name: libwatch-build

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python3 -m pip install -e .
      - run: python3 -m libwatch
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
